platform :ios, '11.0'
inhibit_all_warnings!

target 'cordova-project' do
    pod 'Cordova', '~> 6.1.1'
    pod 'CordovaPlugin-camera'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end